apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
  namespace: todo-app
type: Opaque
data:
  # echo -n 'password' | base64
  postgres-password: cGFzc3dvcmQ=
  postgres-user: cG9zdGdyZXM=
  redis-password: ""
  spring-datasource-username: cG9zdGdyZXM=
  spring-datasource-password: cGFzc3dvcmQ=